// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	vk "github.com/timfame/vk-api.git/vk"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// NewsfeedSearch provides a mock function with given fields: ctx, request
func (_m *IClient) NewsfeedSearch(ctx context.Context, request *vk.NewsfeedSearchRequest) (*vk.NewsfeedSearchResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *vk.NewsfeedSearchResponse
	if rf, ok := ret.Get(0).(func(context.Context, *vk.NewsfeedSearchRequest) *vk.NewsfeedSearchResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vk.NewsfeedSearchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *vk.NewsfeedSearchRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
